ALTER TABLE `order_temp` ADD FOREIGN KEY (`design_id`) REFERENCES `phone_designs`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT; ALTER TABLE `order_temp` ADD FOREIGN KEY (`member_id`) REFERENCES `member_list`(`sid`) ON DELETE RESTRICT ON UPDATE RESTRICT; ALTER TABLE `order_temp` ADD FOREIGN KEY (`model_id`) REFERENCES `phone_models`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT; ALTER TABLE `order_temp` ADD FOREIGN KEY (`series_id`) REFERENCES `phone_series`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT; ALTER TABLE `order_temp` ADD FOREIGN KEY (`shell_id`) REFERENCES `phone_shells`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;



ALTER TABLE `order_list` ADD FOREIGN KEY (`member_id`) REFERENCES `member_list`(`sid`) ON DELETE RESTRICT ON UPDATE RESTRICT;



ALTER TABLE `order_detail` ADD FOREIGN KEY (`design_id`) REFERENCES `order_detail`(`sid`) ON DELETE RESTRICT ON UPDATE RESTRICT; ALTER TABLE `order_detail` ADD FOREIGN KEY (`model_id`) REFERENCES `phone_models`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT; ALTER TABLE `order_detail` ADD FOREIGN KEY (`order_id`) REFERENCES `order_list`(`sid`) ON DELETE RESTRICT ON UPDATE RESTRICT; ALTER TABLE `order_detail` ADD FOREIGN KEY (`series_id`) REFERENCES `phone_series`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT; ALTER TABLE `order_detail` ADD FOREIGN KEY (`shell_id`) REFERENCES `phone_shells`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;